apiVersion: v1
kind: Service
metadata:
  name: analytics-dashboard-service
  namespace: ${K8S_NAMESPACE}
  labels:
    app: analytics-dashboard-service
    tier: backend
spec:
  selector:
    app: analytics-dashboard-service
  ports:
  - port: 8050
    targetPort: 8050
    protocol: TCP
    name: http
  type: ClusterIP
